### ISSUE TITLE
React 0.13 support

### ISSUE THREAD

**Issue by denisw** [STRML/react-router-component#128]
This library can't currently be used with React 0.13 because it lists React `0.12.x` as a `peerDependency`. It would be nice if it would be usable with 0.13.x too.

**Comment by jsg2021** [comment]
^0.12.x actually would accept 0.13.x.  ~0.12.x would not.  The real breaker is react-async. It needs updating.

It would be nice to split the async parts of this router out into a separate package. (since react-async is an anti-pattern)

**Comment by STRML** [comment]
Hey - `^0.12.x` actually doesn't include `0.13.x`; the caret syntax includes a full major version only in majors >= 1.

In any case, we've updated react-async and this module to support 0.12 and 0.13 since there are no major changes that would affect either module.

I agree about splitting out react-async, I'd like to drop the dep as well. I'll open a separate ticket.
