### ISSUE TITLE
How to make an Active Link?

### ISSUE THREAD

**Issue by johnmcdowall** [STRML/react-router-component#154]
The recipe is over 2 years old, and no longer works. 

What is the current method of producing an active link?

**Comment by jsg2021** [comment]
It does work:

```
var React = require('react');
var Router = require('react-router-component');
var cx = require('classnames');

var HighlightedLink = React.createClass({
    mixins: [Router.NavigatableMixin],

    isActive: function() {
        // getPath() returns the path of the active Location in the current router.
        return this.getPath() === this.props.href
    },

    render: function() {
        var activeClassName = this.props.activeClassName || 'active';
        return (
            <Router.Link {...this.props} className={cx(this.props.className, {[activeClassName]: this.isActive()})} /> 
        );
    }
});
```

If you are wanting to activate the link when the current path is deeper than the initial, then you will have to do a startsWith test instead of an equality.

If your link is not mounted as a descendant of the `Locations` component, then no, it will not work as is.  You will have to make it compare the complete URL
